CREATE TABLE registrations (Firstname VARCHAR , Lastname VARCHAR, Ranking SMALLINT, FideID INTEGER PRIMARY KEY );
CREATE TABLE login(ID SMALLINT AUTO_INCREMENT PRIMARY KEY CHECK(ID<1),Username VARCHAR UNIQUE, Password VARCHAR,Salt VARCHAR);
